name: PigRPGLore
main: com.github.xzzpig.pigrpglore.Main
version: V0.1
author: xzzpig
depend:
- PigRPGCore
commands:
  pigrpglore: 
    description: PigRPGLore的主命令
    usage: /prl help
    aliases:
    - prl