name: MultiServerChat
main: com.github.xzzpig.multiserverchat.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  multiserverchat: 
    description: MultiServerChat的主命令
    usage: /msc help
    aliases:
    - msc