name: PigUtilsPlugin
main: com.github.xzzpig.pigutilsplugin.Main
version: V0.1
author: xzzpig
commands:
  pigutilsplugin:
    description: PigUtilsPlugin的主命令
    usage: /pigutilsplugin help
    aliases:
    - pup
permissions: 
  pigutilsplugin.reload: 
    default: op
    description: 命令/pup reload 的权限
  pigutilsplugin.list: 
    default: op
    description: 命令/pup list 的权限