name: PigRPGCore
main: com.github.xzzpig.pigrpgcore.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  pigrpgcore:
    description: PigRPGCore的主命令
    usage: /prc help
    aliases:
    - prc
    - pigrc
    - pigrpgc