Lord:
  Notice:
    time: 60
    command_times: 16
    command_delay: 0
    content:
    - 公告事例1
    - 公告事例2
  shop:
　　 Example:
　　   EID: 1
　　   Price: 0
　　   Permission: null
　　   Exp: 0
　　   Honor: 0