batedamage: 
  no_count_entity: 
    - Chicken
    - Cow
    - Horse
    - MushroomCow
    - Ocelot
    - Pig
    - Sheep
    - Villager
  permission: 
    1: 
      - example.1
    2: 
      - example.2
      - example.3