name: Lord
main: com.github.xzzpig.lord.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  lord:
    description: Lord的主命令
    usage: /lord help
permission:
  lord.*:
    description: Lord的所有权限
    default: op
    children:
      lord.admin.*: true
  lord.admin.*:
    description: Lord的管理员权限
    default: op
    children:
      lord.default.*: true
      lord.admin.command.*: true
  lord.defalut.*:
    description: Lord的普通权限
    default: op
    children:
      lord.default.command.*: true
  lord.admin.command.*:
    description: Lord的管理员命令权限
    default: op
    children:
      lord.admin.command.notice: true
  lord.admin.command.notice:
    description: Lord notice的命令权限
    default: op
  lord.default.command.*:
    description: Lord的普通命令权限
    default: op
    children:
      lord.default.command.market.open: true
      lord.default.command.market.create: true
  lord.default.command.market.open:
    description: 打开市场权限
    default: op
  lord.default.command.market.create:
    description: 上架物品权限
    default: op