name: PigServerManager
main: com.github.xzzpig.psm.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  PigServerManager: 
    description: PigServerManager的主命令
    usage: /psm help 查看帮助
    aliases:
    - psm
permissions:
  pigservermanager.admin:
    description: PigServerManager的所有权限
    default: op