name: PrefixManager
main: com.github.xzzpig.prefixmanager.Main
version: V0.1
author: xzzpig
depend: [PigAPI]
commands:
  prefixmanager: 
    description: PrefixManager的主命令
    usage: /pm help
    aliases: [pm]