name: CreativeInWorld
main: com.github.xzzpig.ciw.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  CreativeInWorld:
    description: CreativeInWorld的主命令
    usage: /ciw help
    aliases:
    - ciw