name: PigAttribute
main: com.github.xzzpig.pigattribute.Main
version: V0.1
author: xzzpig
depend:
- PigAPI
commands:
  pigattribute: 
    description: pigattribute的主命令
    usage: /pa help
    aliases:
    - pa
